export const ACTUALIZAR_PRUEBA = 'ACTUALIZAR_PRUEBA'

//Album
export const ACTUALIZAR_ALBUM = 'ACTUALIZAR_ALBUM'
export const ACTUALIZAR_SELECTED_ALBUM = 'ACTUALIZAR_SELECTED_ALBUM'

//photos
export const ACTUALIZAR_PHOTOS = 'ACTUALIZAR_PHOTOS'

